@startuml
'https://plantuml.com/class-diagram

interface Element {
  + double getValue()
  + Stack<Element> accept(Stack<Element> stack)
  + String toDisplayString()
}

class NumberElement implements Element {
  - double value
  + NumberElement(double value)
}

interface OperatorElement implements Element {
  + String getToken()
}

enum BinaryOperator extends OperatorElement {
  - token: String
  + PLUS
  + MINUS
  + TIMES
  + DIVIDE
  + String getToken()
  double apply(double a, double b)

}
enum UnaryOperator extends OperatorElement {
  + SIN
  + COS
}

hide empty members

@enduml